# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.1
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - pod --version
  - pod lib lint --allow-warnings
  - set -o pipefail && xcodebuild test -workspace Example/Kiwi-CedarShortcuts.xcworkspace -scheme "Example Specs" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
